### ISSUE TITLE
[Solved] Settings reset after browser close on Firefox

### ISSUE THREAD

**Issue by e4BdSBmUzHowFico5Ktn** [tarampampam/random-user-agent#113] opened 2020-01-26 08:42 UTC
## Describe the bug

When closing and opening firefox, the settings (time to refresh, which user agents etc) reset to the default (10 mins and only chrome browsers).
This is a problem for me when using google websites like Youtube, as these sites don't work in Firefox when the website expects a Chrome browser. This causes the site to completely break.
I`ve had this for months now and am pretty done with this so decided to post an issue.

### Expected behaviour:

Settings should be stored somehow after closing the browser.

### Actual behaviour:

When closing and opening firefox, the settings (time to refresh, which user agents etc) reset to the default (10 mins and only chrome browsers).

### Steps to reproduce the behavior:

Use Firefox and only Chrome based user agents
Go to Youtube

This might be caused by some interaction with other plugins and/or firefox settings. If you have any insights, please let me know.

### Desktop (please complete the following information):

 - OS: [e.g. `iOS`, `Linux`, `Windows`]
Ubuntu derivative
 - Browser: [e.g. `Chrome`, `Firefox`]
Firefox, all most recent versions of the past few months
 - Version: [e.g. `67.0.3396.62 64 bit`]
72.0.1 64 bit
 - User Agent under which the issue appears: [e.g. `Chrome 70`, `Firefox 62`]
Any of the Chrome on *OS

**Comment by neroux** [comment] 2020-01-26 09:12
That is most likely a duplicate of #56, #90, and #100.

**Comment by e4BdSBmUzHowFico5Ktn** [comment] 2020-01-26 10:08
Thanks for the quick reply! 
I've managed to fix it, however, I did not want to disable sync as in #90 and #100
In go to: `about:preferences#privacy` I had this on: 'Delete cookies and site data when Firefox is closed'

My fix was:
go to: `about:preferences#privacy`
Under `Cookies and Site Data` go to `Manage Permissions...` and fill in `addons.mozilla.org` and click `allow` and `save changes`
This stores the addon data between closes of Firefox

**Closed** 2020-01-26 11:13 UTC
Labels: Duplicate, Firefox-only, Question
