### ISSUE TITLE
Youtube issue

### ISSUE THREAD

**Issue by qarliv** [tarampampam/random-user-agent#110] opened 2019-10-01 16:43 UTC
## Describe the bug

> Youtube main page is not loading on Firefox v69.

### Expected behaviour:

> Youtube should load.

### Actual behaviour:

> The page shows no info.

### Steps to reproduce the behavior:

 2. Click on '...'
 3. See error

### Screenshots

> If applicable, add screenshots to help explain your problem.
>
> Google Chrome: **Menu → Settings → More tools → Extensions → Developer mode (check) → Random User-Agent → Background Page** → [Press **PrtScn**]

### Desktop (please complete the following information):

 - OS: Windows 10
 - Browser: Firefox
 - Version: 69.0.1 64 bit
 - User Agent under which the issue appears: Firefox 62

## Additional context

> Add any other context about the problem here.

**Comment by neroux** [comment] 2019-10-01 17:46
Seems to load just fine

![image](https://user-images.githubusercontent.com/24754773/65986274-d06a8000-e483-11e9-80a4-9c47c1740a69.png)

Also, RUA does not offer Firefox 62 any more, so you must have configured a custom user agent, correct?

Please make sure this issue is not just a duplicate of https://github.com/tarampampam/random-user-agent/issues?q=label%3A%22Browser+sniffing%22

**Comment by neroux** [comment] 2019-10-06 16:02
No response, closing.

**Closed by neroux** 2019-10-06 16:02 UTC

**Comment by qarliv** [comment] 2019-10-07 14:56
Hi, Thx. for your answer.
I disabled RUA for Youtube domain and it loads just fine now.

**Comment by neroux** [comment] 2019-10-07 15:04
It probably is aforementioned browser sniffing issue.
