### ISSUE TITLE
There will be a problem of not being able to use the user agent.

### ISSUE THREAD

**Issue by e-tw** [tarampampam/random-user-agent#566] opened 2024-04-17 08:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,
The RUA extension is unresponsive after Chromium adds a command line.
"chome.exe --user-agent"

### Browser

Chrome

### Extension version

3.19.0

### Anything else?

Hello,
Is it possible to add a forced overwrite action?

@tarampampam

**Comment by tarampampam** [comment] 2024-05-11 23:00
Hello there! Could you please test the alpha version of a new major version (v4) from issue #572? Does the problem still reproduce even with it?

**Comment by tarampampam** [comment] 2024-05-13 16:30
I'm closing this issue because the described problem seems to be fixed in the new version, which was released recently (here is the [link](https://github.com/tarampampam/random-user-agent/releases/tag/v4.0.0)). Feel free to reopen it or ping me if it still brings any problems. Thank you for reporting the issue and for your attention to this project! 👍🏿

**Closed by tarampampam** 2024-05-13 16:30 UTC
Labels: type:bug
