### ISSUE TITLE
Hope the automatically generated user agent conforms to the official default style

### ISSUE THREAD

**Issue by TGQOTO** [tarampampam/random-user-agent#525] opened 2023-12-13 16:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

i like this extension.Keep up the good work!

My edge browser default is:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0

When only the extension's Edge Windows switch is turned on, the generated user agent is as follows:
Mozilla/5.0 (Windows NT 11.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5744.219 Safari/537.36 Edg/113.0.1620.46

The difference is the default user agent for the Edge browser includes only the major version number and does not include the minor version. Moreover, the user agent for both Chrome and Edge should have the same version number, but the generated user agents are different.

The difference in Chrome browser is the same as in Edge. 
I hope you can update it in the next version to make the generated user agent conform to the official default. This way, it will be able to blend in with the large number of users. 

Thank you very much.

**Comment by tarampampam** [comment] 2024-05-11 23:02
Hello there! Could you please test the alpha version of a new major version (v4) from issue https://github.com/tarampampam/random-user-agent/issues/572? Does the problem still reproduce even with it?

**Comment by tarampampam** [comment] 2024-05-13 16:31
I'm closing this issue because the described problem seems to be fixed in the new version, which was released recently (here is the [link](https://github.com/tarampampam/random-user-agent/releases/tag/v4.0.0)). Feel free to reopen it or ping me if it still brings any problems. Thank you for reporting the issue and for your attention to this project! 👍🏿

**Closed by tarampampam** 2024-05-13 16:31 UTC
Labels: type:feature_request
