### ISSUE TITLE
Disabling sync prevents saving of configuration

### ISSUE THREAD

**Issue by acritum** [tarampampam/random-user-agent#56] opened 2018-04-14 06:03 UTC
Running Linux mint cinnamon latest version. Installed Firefox for linux and this plugin (all latest versions). The problem is that the plugin shows "User-Agent (managed by this extension) is not available", but "get new agent" button makes it work. But, after closing Firefox and starting it again, all settings are reset to default and "User-Agent (managed by this extension) is not available" is shown again. I used the same version on Windows 7 and it worked. I thought it may deal with some other plugins, so I disabled all other plugins, but the problem is still there. What can it be?

**Comment by neroux** [comment] 2018-04-14 08:04
I am afraid I wont be able to give a concrete answer straight away, as that might be a tricky one to debug.

It would seem the settings of the extension cant be saved properly. Do you experience anything of that sort with any other Firefox extension? Could it be something profile related, file/directory permission for example?

Could you try to create a new Firefox profile and check if you experience the issue there as well?

**Comment by ernsteiswuerfel** [comment] 2018-04-14 16:35
Same problem here. I created a new profile, added Random User Agent as only Extension, but the problem persists.

Looks like the settings can't be saved. If I change something it works for the session, but if I close and restart FF it starts with default settings and "User-Agent (managed by this extension) is not available".

**Comment by neroux** [comment] 2018-04-14 18:31
@acritum Please, more information about reproducability would definitely help. As for containers, I cant comment on that yet, I would need to test it myself. Please try it with a fresh browser profile as well.

@ernsteiswuerfel A brand new profile? That should be easy to reproduce then :) Any particular Firefox version? Operating system?

**Comment by neroux** [comment] 2018-04-14 18:41
Unfortunately I dont seem to be able to reproduce it.

I just installed the extension in a fresh profile using the latest Nightly (61.0, April 14th) and the settings to get stored. I also tested it with and without containers, works for both.

Could you maybe debug the extension by going to about:debugging#addons, ticking the debug checkbox, and going down to the extension and open the debug console? Is there any output? It seems there is one "null" error shown but that does not seem to influence the saving of the settings.

**Comment by neroux** [comment] 2018-04-14 19:47
The error I referred to should be fixed with a865956, however - as mentioned - it shouldnt be the reason for the error you experience.

**Comment by neroux** [comment] 2018-04-14 20:39
I just published 2.2.3 which includes a865956, though I am still not sure that will fix it, as I couldnt reproduce it without that fix either. Maybe you can give it a quick check.

**Comment by acritum** [comment] 2018-04-15 04:35
I've made some tests: it works with a new profile, however, it doesn't in my profile. Disabling all other extensions doesn't help, which means the problem has something to do with my FF settings. It's still a long way to find what settings prevent the extension from running and saving its settings. What's more confusing is that the extension CAN show fake user-agent after manually renewing the user agent (Get new agent button), but it doesn't want to renew it every 1 minute if I set it in the settings. Version 2.2.3 doesn't help. I will let you know if I find something.
![useragent](https://user-images.githubusercontent.com/6622765/38775022-50386676-407f-11e8-8b82-13e00bb6923f.png)

**Comment by neroux** [comment] 2018-04-15 07:38
Thanks, I suspect it might have something to do with how extensions save their settings in your profile. It seems RUA can persist it own. **Have you tried the extension debugging I mentioned earlier?**

If you want you could also share the *prefs.js* file from your profile, in that way I could try to reproduce it with your settings. Just remove everything from it that might be privacy sensitive (and lets hope none of those settings is the reason for the behaviour :D )

**Comment by acritum** [comment] 2018-04-15 16:33
Thanks, extension debugging helped. webextensions.storage.sync.enabled was set to false, and when I set it to true, it started to work. This extension doesn't work with webextensions.storage.sync.enabled=false, and I think this is not good. Is it possible to make this extension work without it?

**Comment by dc9f7839** [comment] 2018-04-15 17:39
Try this on firefox if i possible:
https://github.com/tarampampam/random-user-agent/issues/12#issuecomment-381423519
I don't know settings directory for extensions with firefox you must find.

**Comment by acritum** [comment] 2018-04-15 18:54
> Setting webextensions.storage.sync.enabled to false should not be too much of a problem, as you could achieve the same by leaving it at true and not adding a Firefox account. No account = no sync, regardless of whether it is enabled or not.

In fact, my goal was to prevent ANY unauthorized connections from FF side, and there are MANY with the default profile. What's worse, the latest versions of FF ignore some user prohibitions, for example, I've got "toolkit.telemetry.enabled=false" and at the same time I saw it in the console that FF tried to connect to toolkit.telemetry.server when the extension had an error. So, it doesn't care if some settings are allowed or disallowed! Finally, if I don't have their account, it doesn't mean that FF will not try to connect to their servers ;-) The only way I was able to prevent ALL stupid connections is by replacing all urls in the config with localhost, and now I have absolutely silent FF (I used Wireshark to test, it was really horrifying with the default settings... there were always many connections even when I didn't open any pages, and now there are none).

> %LocalAppData%\Slimjet\User Data\Default\Sync Extension Settings\einpaelgookohagofgnnkcfjbkkgepnpLocal Extension Settings\einpaelgookohagofgnnkcfjbkkgepnp" to
"%LocalAppData%\Slimjet\User Data\Default\Sync Extension Settings\einpaelgookohagofgnnkcfjbkkgepnp"

I'm not sure how to do it in FF because I don't see anything that resembles these directories in the profile. There is "extension-settings.json" but I'm not sure that it's what I need. I can live with webextensions.storage.sync.enabled=true as webextensions.storage.sync.serverURL points to http://127.0.0.1 anyway and they won't get anything from my side even if they try, but I hope that the workaround will be built into the extension someday, because other extensions don't seem to require that storage sync...

**Comment by neroux** [comment] 2018-04-15 19:24
> Finally, if I don't have their account, it doesn't mean that FF will not try to connect to their servers

No, but it cant sync your data without an account. Of course they could still send your data but that does not depend on a flag either.

> I hope that the workaround will be built into the extension someday

I hope it wont be just a workaround :) but a proper fix for #12 - pull requests most welcome :)

**Comment by ernsteiswuerfel** [comment] 2018-04-16 01:02
Thanks for your efforts!

I can confirm, that setting webextensions.storage.sync.enabled=true works. OS is Gentoo Linux, FF 52.6 64bit.

**Comment by neroux** [comment] 2018-04-17 18:41
@acritum @ernsteiswuerfel There is a preliminary test version with a fix for #12 as well as for this issue at https://github.com/tarampampam/random-user-agent/releases/download/sync/random_user_agent-2.2.3t1-an.fx.xpi

Could you quickly test it and give me some feedback?

**Comment by acritum** [comment] 2018-04-18 03:45
2.2.3t1 works with webextensions.storage.sync.enabled=false in my system, many thanks!

**Comment by neroux** [comment] 2018-04-21 06:43
Thanks for the feedback @acritum. If there are no issues reported, that version should go live within the next week.

**Comment by neroux** [comment] 2018-04-21 12:03
I remember, it was the issue that Google sends different/incompatible JavaScript in these cases (#41).

What you suggested would be definitely a welcome addition, there is in fact such an open feature request at #45, but I cant make any promise as to how quickly I could add it - pull requests more than welcome of coure :sunglasses:. Please lets continue a discussion about that particular feature in #45 though :)

**Comment by neroux** [comment] 2018-04-28 13:25
2.2.4 for Firefox is out.

**Closed by neroux** 2018-04-28 13:25 UTC
Labels: Error / bug, Firefox-only
