### ISSUE TITLE
window.navigator.platform does not work

### ISSUE THREAD

**Issue by lzatsc** [tarampampam/random-user-agent#366] opened 2022-10-20 15:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

amiunique.org and similar services detects WIN PLATFORM when you use an Iphone or any other user agent.
when you use an IPHONE agent, amiunique.org should show platform = iphone

### Steps to reproduce

GENERATOR SETTINGS > select only the safari on iphone option.
amiunique.org and similar services detects WIN PLATFORM when you use an Iphone or any other user agent.
when you use an IPHONE agent, amiunique.org should show platform = iphone
( maybe in future you could also add a platform field in the general settings )

### Browser

Firefox

### Extension version

4.14.2

### Anything else?

with this bug google will Know it is not an iphone but it is a windows computer and so it triggers all the captcha making it impossible to use the extension.  please help to fix this. your is a beautiful extension!

**Comment by tarampampam** [comment] 2022-10-20 16:24
![Screenshot at 2022-10-20 20-19-19](https://user-images.githubusercontent.com/7326800/197004481-8c120770-d646-48f4-8e01-13c49ec3ffce.png)

It looks like a site script issue because my real OS is Linux, but on the page, I see "Win32" (console output is on the screenshot).

Could you please provide more examples?

**Comment by tarampampam** [comment] 2022-10-20 16:33
But in the incognito mode, all looks fine:

![Screenshot at 2022-10-20 20-28-56](https://user-images.githubusercontent.com/7326800/197006066-67339397-981e-4108-ab74-d6a0923a492a.png)

Are you sure that the problem is with this extension and not with the way you are scraping data from the target resource?

**Comment by tarampampam** [comment] 2022-10-21 07:59
In Firefox all work fine too. I'm closing this issue.

![](https://user-images.githubusercontent.com/7326800/197144100-1c6ece5a-95a5-4961-90f8-21d9cb1a0724.png)

**Closed by tarampampam** 2022-10-21 07:59 UTC
Labels: type:bug

**Comment by tarampampam** [comment] 2022-10-22 08:32
Feel free to provide more details for reproducing described behavior, I will re-open this issue in this case.
