### ISSUE TITLE
Cloudflare Verification

### ISSUE THREAD

**Issue by sixgodfan** [tarampampam/random-user-agent#488] opened 2023-07-13 17:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When used on vidival, the Cloudflare real-person verification button cannot be clicked, and the automatic cycle refreshes, failing to pass

### Browser

Other

### Extension version

new

**Comment by tarampampam** [comment] 2023-07-14 07:10
Duplicate of https://github.com/tarampampam/random-user-agent/issues/304

**Closed by tarampampam** 2023-07-14 07:10 UTC
Labels: type:bug
