### ISSUE TITLE
Cannot use it with chromedriver selenium python

### ISSUE THREAD

**Issue by piotrros** [tarampampam/random-user-agent#19] opened 2017-06-14 16:01 UTC
Normally extension works fine, but I want to use it with selenium webdriver (python bindings). Other extension work, but this isn't. I'm getting the following error:

```
  File "/usr/local/lib/python2.7/site-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/site-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 188, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: **Message: unknown error: failed to wait for extension background page to load: chrome-extension://einpaelgookohagofgnnkcfjbkkgepnp//html/background.html
from unknown error: page could not be found: chrome-extension://einpaelgookohagofgnnkcfjbkkgepnp//html/background.html**
  (Driver info: chromedriver=2.30.478461 (8b6b2938ac9f3a090d2cf8bafbe8ca73dcbf7945),platform=Mac OS X 10.12.5 x86_64)
```

Where's the problem and how can I fix this?

**Comment by tarampampam** [comment] 2017-08-03 08:31
Can you show **browser** log?

**Comment by piotrros** [comment] 2017-08-08 16:40
I tried enabling browser logs as stated here:
https://www.chromium.org/for-testers/enable-logging

but there's no chrome_debug.log :(

**Comment by neroux** [comment] 2017-12-08 22:33
From a quick web search it would appear the issue is fixed with the latest chromedriver version. Could you confirm @piotrros?

**Closed** 2017-12-11 22:15 UTC
