### ISSUE TITLE
Cloudflare loop with whitelist mode

### ISSUE THREAD

**Issue by meichengg** [tarampampam/random-user-agent#304] opened 2022-05-19 07:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm having infinite loop when accessing webpages using Cloudflare as WAF such as gitlab.com and jetbra.in, it keeps reloading after 5 seconds, the only way to fix this problem is to turn off whitelist mode in the settings (it also disables the extension itself 🤦🏻 ).

### Steps to reproduce

1. Go to [https://gitlab.com/users/sign_in](https://gitlab.com/users/sign_in) or [https://jetbra.in/](https://jetbra.in/).
2. The loop starts.
3. Turn off whitelist mode in the extension settings.
4. Reload those webpages, it will pass.

### Browser

Chrome

**Comment by tarampampam** [comment] 2022-05-19 07:53
Hi @meichengg! I can't reproduce described behavior... For example, https://jetbra.in/ opens without the loop:

 
![image](https://user-images.githubusercontent.com/7326800/169241997-a8c519d3-d646-4d41-a3a9-70646be094e6.png)

**Comment by meichengg** [comment] 2022-05-19 07:54
I'm using Chrome 102.0.5005.61 (macOS Monterey) by the way, sorry for the missing info.

**Comment by tarampampam** [comment] 2022-05-19 07:58
Ok, I will check on mac a little bit later, ok?

**Comment by meichengg** [comment] 2022-05-20 03:20
I think you should check this out and you can try with [animedao.com](animedao.com).

[https://support.mozilla.org/kn/questions/1347179](https://support.mozilla.org/kn/questions/1347179)

**Comment by meichengg** [comment] 2022-05-20 04:24
I also checked on Windows, i think Cloudflare checks if the user agent is valid, in this case it's kinda wrong so the user gets the loop.

![image](https://user-images.githubusercontent.com/25204246/169450189-8afd2f14-8abb-4ff5-b78a-42020ed361e3.png)

**Comment by tarampampam** [comment] 2022-05-20 07:18
Are you sure you don't have any other installed extensions that might be interfering with the site's functionality? Could you disable all of them for a test?

**Comment by meichengg** [comment] 2022-05-20 07:34
Yes, i turned all the other extensions off, the only left was this extension. I retested with those websites i mentioned above and all give me infinite loop but only one working.

loop:
Mozilla/5.0 (X11; U; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4861.82 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; WOW64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4852.142 Safari/537.36

working:
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4859.209 Safari/537.36

**Comment by fakhamatia** [comment] 2022-09-10 09:07
I have the same problem
What do you need me to share?

**Comment by tarampampam** [comment] 2022-09-27 13:09
Buddies, I have reproduced described behavior, but haven't any idea (right) how to fix this issue, except the disabling replacing on the domain while checking is not passed. Sorry for that :(

**Comment by meichengg** [comment] 2022-09-27 13:47
> Buddies, I have reproduced described behavior, but haven't any idea (right now) how to fix this issue, except the disabling replacing on the domain while checking is not passed. Sorry for that :(

its okay, you did great, we will find other workarounds, thanks anyway

**Comment by TheGITofTeo997** [comment] 2023-01-30 13:18
Hello, I just wanted to report that I am facing the same issue even with other user agent spoof extensions. 
It looks like there is some issue when cloudflare serves the challenge and verifies your agent.

I've also tried to whitelist some domains: 

- cloudflare.com
- hcaptcha.com
- challenges.cloudflare.com
- a.nel.cloudflare.com
- cf-assets.hcaptcha.com

Unfortunately this does not solve the issue.
The challenge will pass only if you get a user agent coherent with your real one, e.g. if you are using Mozilla like me, every Firefox user agent on every platform will work, but if you attempt to set a Chrome one for example, you get the loop.

The only workaround to this, unfortunately, is to blacklist even the target domain you are trying to access behind the challenge.
I hope this is achievable in some way and that this is useful info.

**Comment by meichengg** [comment] 2023-02-22 03:08
I can confirm that i'm using the Chrome on macOS and the only option that i choose is Chrome for macOS which i still get the loop.

![image](https://user-images.githubusercontent.com/25204246/220511283-1f5f5e73-833d-4740-ab4f-27296403c254.png)

**Comment by meichengg** [comment] 2023-03-02 03:54
@tarampampam , i found the root cause of this problem, check this out.

https://www.zenrows.com/blog/bypass-cloudflare#cloudflare-active-bot-detection-techniques:~:text=In%20the%20context,live%20demo.

**Comment by philiparvidsson** [comment] 2023-08-03 05:00
Same problem here.

**Comment by Auzhie14** [comment] 2023-08-23 05:52
How to overcome cloudflare verification?? Can not enter

**Comment by yozachar** [comment] 2024-04-28 14:44
I had to pause the agent temporarily :(

**Comment by tarampampam** [comment] 2024-04-28 14:47
I'm working on a new major version of the extension. Please, be patient, I'll do everything that I can to resolve this issue in a new version, I promise

**Comment by tarampampam** [comment] 2024-05-11 22:57
I have great news - the Cloudflare infinite loop appears to be fixed in the new version (v4)! More details can be found here: #572

If anyone can help with testing, links to the alpha build can be found using the link above. Your assistance will be greatly appreciated!

**Comment by tarampampam** [comment] 2024-05-13 16:29
I'm closing this issue because the described problem seems to be fixed in the new version, which was released recently (here is the [link](https://github.com/tarampampam/random-user-agent/releases/tag/v4.0.0)). Feel free to reopen it or ping me if it still brings any problems. Thank you for reporting the issue and for your attention to this project! 👍🏿

**Closed by tarampampam** 2024-05-13 16:29 UTC
Labels: type:feature_request

**Comment by tarampampam** [comment] 2024-05-17 12:02
> i have the chrome extension 4.0.1 version and chatgpt.com has the cloudflare loop again

Could you record a short video to show how it looks on your side?

**Comment by tarampampam** [comment] 2024-05-17 12:46
Thank you! Could you also try the latest version (4.0.2) and, if possible, share screenshots of your settings? I'm asking because I just tested it, and the captcha challenge passed successfully without repeating (in other words, I can't reproduce the issue)

**Comment by tarampampam** [comment] 2024-05-17 13:29
Unfortunately, I'm still not able to reproduce:


https://github.com/tarampampam/random-user-agent/assets/7326800/c485327d-9bd9-480d-be4d-c9fb167d1a16

**Comment by gnz1123** [comment] 2024-05-18 10:13
Version 4.0.2 cannot pass Cloudflare's CAPTCHA verification.

**Comment by meichengg** [comment] 2024-05-20 02:50
@adriadam10 @gnz1123 Are you guys using any VPN service?
